language: java
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
after_success:
- mvn cobertura:cobertura coveralls:report
deploy:
  provider: heroku
  api_key:
    secure: Z2AyRPmCpNykkn7EDVabdOwNc+v9pJl5kZelXZJPTKsv6GkJHaN/k69owOy7xUck4BY+DuJV+N9hN6cb15aorlYWO+y+WxCBtC8rUi0zQhfZtm/ngzTc9g7zzYVvBuOMqkYzOBL+ZfqU0I85X2mtTvSZvLx73VBgpfuwJp+kbs4=
  app: mighty-dusk-3589
  on:
    repo: evsheino/TravelExpenses
notifications:
  slack:
    secure: FIQ8ojj3UdUbx11mEW3FsXplyQf8FXm3xWHlwPKR3ILDMzPRwXCBTXUsApC9b463ndo39oHJH6wju44VkaehNRN/TPja4Aac1z0Z/PEI6/fnsw87B8r3TVThOtw91Oat+rb6LCgSD6JaLe2vw9PcnG6t6C9yIYvImwqVuvb1xu8=
