language: java
after_success:
- mvn clean cobertura:cobertura coveralls:report
deploy:
  provider: heroku
  api_key:
    secure: kUBOQZ72tQri0lZvFY3+rrHBPeU8p2qrEPTSJh7/XFUndEbOZbVINjyF8GCsJJZS5dNnAXJEHa9um/7hP2h1ohK+FQUh4MIBo1aLzPfMwZm8bkLsZfjxF9fGcIcgsniBkKn1xlq6pxHxIgp0PEIdFkFObPY/cI1Cptz+G1tu4Pc=
  app: obscure-river-7179
  on:
    repo: evsheino/TravelExpenses
notifications:
  slack:
    secure: FIQ8ojj3UdUbx11mEW3FsXplyQf8FXm3xWHlwPKR3ILDMzPRwXCBTXUsApC9b463ndo39oHJH6wju44VkaehNRN/TPja4Aac1z0Z/PEI6/fnsw87B8r3TVThOtw91Oat+rb6LCgSD6JaLe2vw9PcnG6t6C9yIYvImwqVuvb1xu8=
