-- Create user table
CREATE TABLE user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) not null,
  username VARCHAR(255) unique not null,
  password VARCHAR(510) not null,
  salt VARCHAR(50) not null);
